### PR TITLE
Very late spring cleaning

### PR DESCRIPTION
**Pull request by theychx**
:dancing_women:

### CODE REVIEW

**Comment by skorokithakis** [comment]
Did `black` not take care of the white space after the docstring?

**Comment by theychx** [comment]
Nope. I'm surprised it didn't complain.

**Comment by theychx** [comment]
Did you see https://github.com/ambv/black/issues/355?

**Comment by skorokithakis** [comment]
I had not, thank you. Hopefully Black will get an opinion about this soon and then we can just upgrade it.

**Pull request merged**
