### PR TITLE
First api mockup

### PR DESCRIPTION
**Pull request by theychx**
Howdy

Here's my attempt at implementing some of what we agreed on.
I realize that it might be more elegant to implement the dynamic creation of cast and cast_controller with some kind of metaclass, so not all "transport" methods have to call ```_create_controller```. I couldn't figure out how to accomplish that though, so suggestions are welcome.

### CODE REVIEW

**Comment by skorokithakis** [comment]
At a first glance, this looks great (minus the small "shure" typo), thank you. We may want to use [attrs](https://github.com/python-attrs/attrs) for the class iself, I will review more thoroughly soon.

**Comment by theychx** [comment]
> minus the small "shure" typo

Hehe, I actually own a Shure microphone. :microphone:

**Comment by theychx** [comment]
I've pushed a slight improvement to the mockup.
Attrs looks really cool, but I'm not sure I understand how this could be of benefit to us for this particular task.

**Comment by skorokithakis** [comment]
Attrs basically gives you all the boilerplate for free, so `device1 == device2` will work, easier instantiation for `__init__` things like that. It's not mandatory, it's just a nice library, although I don't know if the extra dependency is worth it here.

**Comment by skorokithakis** [comment]
Hey, sorry this took so long. Looks good, merge at will!

**Comment by skorokithakis** [comment]
Oh, also, I'm making a thing I'd like to recruit you for, if you're interested! Super early days still, but it's [a volunteer maintainer community](https://www.codeshelter.co/).

**Comment by theychx** [comment]
Code Shelter sounds cool. Count me in!

**Comment by skorokithakis** [comment]
Awesome, I'm implementing maintainer login now, I'll ask you to log in at some point so you can get notifications for new repositories and things, thanks man!

**Pull request merged**
