### PR TITLE
[api] fix for 404 issues

### PR DESCRIPTION
**Pull request by theychx**
as discussed in #139

### CODE REVIEW

**Comment by skorokithakis** [comment]
Oh wait, why was this closed? Are you not merging it?

**Comment by theychx** [comment]
Sorry, this is hurting my brain. How do I go about this, now that I've pushed this (including your changes)?

**Comment by skorokithakis** [comment]
```
git checkout api-fix
git merge master
git push
```
Done!

**Comment by skorokithakis** [comment]
(And then reopen the PR/make a new PR)

**Comment by skorokithakis** [comment]
Ah, then you can merge my changes into `api-develop` and open the PR, or just branch `api-fix` off `api-develop`.

**Pull request closed without merging**
