### PR TITLE
Remove py2 compat code

### PR DESCRIPTION
**Pull request by theychx**
As discussed in #57 (CI failed because of weird 403's from vimeo, thus the junk commits).

### CODE REVIEW

**Comment by theychx** [comment]
Wow, this is annoying. I'll fix the tests, so we don't rely on Vimeo.

**Comment by skorokithakis** [comment]
Fantastic, thanks! Semver dictates that the next release should be 1.0.0, so I guess we better do that. Is there anything else you need to add before then? Perhaps the local-serving rework?

**Comment by theychx** [comment]
> Semver dictates that the next release should be 1.0.0

Could you elaborate on that? Seems to me that we're still not quite there (I did read https://semver.org/#how-do-i-know-when-to-release-100).

> Is there anything else you need to add before then? Perhaps the local-serving rework?

Yep, definitely the local-serving rework. I'd also like to add some form of save/restore mechanism, so users can save media location and seek position on a device & app basis, and then recall it later at their leisure.

**Comment by theychx** [comment]
.....and subtitles support          ...........and a option to force the use of the default controller, in case a custom controller stops working.

**Comment by skorokithakis** [comment]
Oh yeah, you're right about semver, I was thinking of "Major version MUST be incremented if any backwards incompatible changes are introduced to the public API" and forgot that 0.x.y is basically "anything goes". Never mind that comment, then!

**Comment by theychx** [comment]
Ok. But it might be worth considering to do the local-serving rework and the force default controller option, and then release. I'm thinking that it is perhaps a bit annoying to python3 users, if the latest version has pins on PyChromecast/zeroconf (I don't mind personally).

**Comment by skorokithakis** [comment]
Yeah, I agree with that. Hopefully I can fix this crashing bug that's been plaguing me in that release as well.

**Pull request merged**
