### PR TITLE
Fix Travis

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by theychx** [comment]
Uhm, I don't know what you're doing either. :rofl:

**Comment by skorokithakis** [comment]
:(

**Comment by theychx** [comment]
Seriously, is this working?

**Comment by skorokithakis** [comment]
Yes, it's all fixed, except Travis has now decided that tests shouldn't run on 3.4 and 3.5, regardless of Black.

**Comment by theychx** [comment]
Well then, I would argue, it is not fixed. We need 3.4 and 3.5 testing.

**Comment by skorokithakis** [comment]
Well, yes, hence all the failures :P

**Comment by skorokithakis** [comment]
I didn't try to get 3.4 tests to run to not get 3.4 tests to run!

**Pull request merged**
