### PR TITLE
Pychromecast9

### LINKED ISSUE #324: error from a system update
any clue for this error
using with home assistant and web terminal  
error with  python 3.8 ????
catt --version
catt v0.12.0, Zaniest Zapper.

catt scan       
Scanning Chromecasts...
Traceback (most recent call last):
  File "/usr/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/catt/cli.py", line 641, in main
    return cli(obj=get_config_as_dict())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/catt/cli.py", line 482, in scan
    devices = get_cast_devices_info()
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 63, in get_cast_devices_info
    devices = get_cast_devices()
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 50, in get_cast_devices
    devices = [CastDevice(pychromecast.get_chromecast_from_service(s, browser.zc), s[4], s[5]) for s in services]
  File "/usr/lib/python3.8/site-packages/catt/discovery.py", line 50, in <listcomp>
    devices = [CastDevice(pychromecast.get_chromecast_from_service(s, browser.zc), s[4], s[5]) for s in services]
AttributeError: module 'pychromecast' has no attribute 'get_chromecast_from_service'

### PR DESCRIPTION
**Pull request by theychx**
Yo yo yo, pychromecast breakage fixed!

fixes #324

### CODE REVIEW

**Comment by skorokithakis** [comment]
Well you are amazing! Let's at least pin to major versions, though, I hate upstream releases breaking our stuff.

**Comment by theychx** [comment]
> Let's at least pin to major versions, though

Pins are even more annoying to users. So far it doesn't bother me.

**Comment by skorokithakis** [comment]
Why are pins more annoying?

**Comment by theychx** [comment]
Because, unless you are installing to some isolated environment, the pin might affect your ability to install other packages that relies on a newer pychromecast release.

**Review by skorokithakis — APPROVED** [review]

**Comment by skorokithakis** [comment]
Merged, thank you!

**Comment by theychx** [comment]
I might add that if we make `pipx install catt` the recommended way of installing, the pin wouldn't matter.

**Comment by skorokithakis** [comment]
That works for me, pipx is a better way of installing cli programs anyway.

**Pull request merged**
