### PR TITLE
Add some missing params in yt-specific cmds

### LINKED ISSUE #175: DefaultCastController object has no attribute clear
In v0.9.2, when I run:
```
catt clear
```

I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 472, in main
    return cli(obj={}, default_map=readconfig())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 256, in clear
    cst.clear()
AttributeError: 'DefaultCastController' object has no attribute 'clear'
```

### PR DESCRIPTION
**Pull request by theychx**
fixes #175

### CODE REVIEW

**Comment by theychx** [comment]
The CI status appears to be stuck at "pending", even though the tests completed a long time ago.

**Comment by skorokithakis** [comment]
ADMIN OVERRIDEEEEEEEEEEEEEEE

**Comment by theychx** [comment]
Hehe thanks! Have you ever seen that before?

**Comment by skorokithakis** [comment]
No, not really, but CI, what can you do.

**Pull request merged**
