### PR TITLE
[WIP] Use new Youtube controller

### PR DESCRIPTION
**Pull request by theychx**
..as featured in ```PyChromecast 2.3.0```.

The new controller is both faster and more stable than the one we are currently using. It's missing ```clear_queue``` functionality though, and thus this is still WIP.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Hey, do you use PyCharm, and if yes, do you have a license for it?

**Comment by theychx** [comment]
Nope, I use vscode (and do not have a PyCharm license).

**Comment by skorokithakis** [comment]
Ah, if you want one, I can give you one.

**Comment by theychx** [comment]
That's very generous of you, but I don't feel like this is the time for me to switch editor.

**Pull request closed without merging**
