### PR TITLE
Change the app name on the YouTube controller

### PR DESCRIPTION
**Pull request by skorokithakis**
Like this says, I didn't like the text "Python" on the YouTube display app, so I hackishly changed it.

### CODE REVIEW

**Comment by skorokithakis** [comment]
I am currently trying to get isort to leave my shit alone.

**Comment by skorokithakis** [comment]
The fucked up thing is that isort works locally, but not in precommit, even though they are the same version.

**Comment by skorokithakis** [comment]
> And besides, wouldn't it be easier to just submit a PR to the casttube repo? I'm sure he wouldn't mind changing that screen text.

Change it to what, though? It's not going to be a parameter that goes through pychromecast.

What's your specific criticism of this?

**Comment by theychx** [comment]
> Change it to what, though? It's not going to be a parameter that goes through pychromecast.

Yeah, fair point.
> What's your specific criticism of this?

I only have a very broad criticism of this, and is that is that it is extremely hackish. Why would we do something like this, to fix such a minor problem?

**Comment by skorokithakis** [comment]
Well, for one, it's not a minor problem to me, I think it looks sloppy to have the app show "Python", of all things. Secondly, there isn't really a downside to this. Because of the try block, any error that happens causes the entire block to just get ignored, so there's no downside.

**Comment by skorokithakis** [comment]
Bump

**Comment by theychx** [comment]
I agree with you that it is suboptimal that the screen text says "Python", it should of course say "Catt" or "Cast All The Things" or whatever. The methology of this PR just bothers me, and the super-arrogant comment you put in the code doesn't help either.

I'm sure it is possible for `casttube` to implement the ability to have the text be whatever we like.

**Comment by skorokithakis** [comment]
Even if `casttube` implements the ability, `pychromecast` still needs to expose it.

What's arrogant about the comment?

**Comment by theychx** [comment]
> Even if casttube implements the ability, pychromecast still needs to expose it 

Yes, but only the included YouTube controller, which is effectively maintained by `casttube`s author.
> What's arrogant about the comment?

*"Some might say this goes too far. I say it doesn't go too far enough"*

Thats pretty arrogant.

**Comment by skorokithakis** [comment]
> Yes, but only the included YouTube controller, which is effectively maintained by casttubes author.

Sure, but we don't use it directly, so how would we pass our text to it?

> Thats pretty arrogant.

https://www.youtube.com/watch?v=UUMdCV-Z7kk

**Comment by theychx** [comment]
> Sure, but we don't use it directly, so how would we pass our text to it?

Eh? 
https://github.com/skorokithakis/catt/blob/eb3e20a8d2629799ff0e0075746f1fa7f2c4f525/catt/controllers.py#L15
https://github.com/skorokithakis/catt/blob/eb3e20a8d2629799ff0e0075746f1fa7f2c4f525/catt/controllers.py#L605
> https://www.youtube.com/watch?v=UUMdCV-Z7kk

LOL, if your intention was to reference that clip, then it is not arrogant, obviously. Pretty easy to miss that context though.

**Comment by skorokithakis** [comment]
>  self._controller = YouTubeController() 

Exactly, so the author of PyChromecast would have to add a parameter too, since we don't instantiate YouTubeSession ourselves.

> Pretty easy to miss that context though.

True, it's an old show. I thought the "too far enough" would have tipped you off though :P

**Comment by theychx** [comment]
> Exactly, so the author of PyChromecast would have to add a parameter too, since we don't instantiate YouTubeSession ourselves.

Yes, the `casttube` author would have to do a PR for `pychromecast`, to update the controller. Which he would have to do anyway, in the case of a new `casttube` release with new functionality.

**Comment by theychx** [comment]
> I thought the "too far enough" would have tipped you off though :P

Hehe, yeah, I've always been kind of slow in the uptake. :smile:

**Comment by skorokithakis** [comment]
Yeah, so we'd have to wait for two pieces of software to be updated. Anyway, if you don't think it's worth it, I'm good with that.

**Pull request closed without merging**
